name: tiko_tiko
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  calendar_view: ^1.4.0
  timelines: ^0.1.0
  fl_chart: ^1.0.0
  flutter_spinkit: ^5.2.1
  flutter_slidable: ^4.0.0
  awesome_snackbar_content: ^0.1.6
  latlong2: ^0.9.1
  cached_network_image: ^3.4.1
  animations: ^2.0.11
  shared_preferences: ^2.5.3
  flutter_map: ^8.1.1
  dartz: ^0.10.1
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  flutter_bloc: ^9.1.1
  dio: ^5.8.0+1
  geolocator: ^14.0.1
  connectivity_plus: ^7.0.0
  bottom_sheet: ^4.0.4
  go_router: ^17.0.0
  maplibre_gl: ^0.24.1
  smswatcher: ^0.0.3
  tflite_flutter: ^0.12.1
  #another_telephony: ^0.4.1
  # ussd_service: ^0.1.1
  #sim_card_info: ^1.0.2
  permission_handler: ^12.0.1
  #ussd_launcher: ^1.0.1
  #ussd_advanced: ^1.1.0
  intl: ^0.20.2
  flutter_map_tile_caching: ^10.1.1
  image_picker: ^1.2.1
  socket_io_client: ^3.1.3
  flutter_local_notifications: ^19.5.0
  animated_notch_bottom_bar: ^1.0.4
  # ussd_service: ^0.1.1
  # sim_data: ^0.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
  assets:
      - assets/images/onboarding1.png
      - assets/images/onboarding2.png
      - assets/images/logo.png

